config/routes.rb
HangmanGame::Application.routes.draw do
  devise_for :users
resources :users  do
  member do
    get :play_game
    post :user_input
  end
end
root :to => "pages#home"

resources :sessions,      :only => [:new, :create, :destroy]

match '/about',   :to => 'pages#about', via: 'get'
match '/help',    :to => 'pages#help', via: 'get'
match '/signup',  :to => 'users#new', via: 'get'
match '/signin',  :to => 'sessions#new', via: 'get'
match '/signout', :to => 'sessions#destroy', via: 'delete'

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  #validates :played, :win, :lose, numericality: {only_integer: true}

  before_create :set_default_values

  private
  def set_default_values
    self.played=0
    self.win=0
    self.lose=0
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :first_name, :last_name, presence: true, format: {with: /\A[a-zA-Z\s .]+\z/, message: "No special characters allowed except space & dot"}
  #validates :gender, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, message: "enter valid email address"}

  before_create :email_to_lower_case

  private
  def email_to_lower_case
    ## convert email to lower case
    self.email = self.email.downcase
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, uniqueness: {case_sensitive: false}, length: {in: 6..25, too_long: "%{count} characters minimum allowed",too_short: "%{count} characters maximum allowed"}
  validates :password, presence: true, length: {in: 6..25, too_long: "%{count} characters minimum allowed",too_short: "%{count} characters maximum allowed"},format: {with: /\d/, message: "Password must contain at least one Number"}
  has_one :profile , dependent: :destroy
  accepts_nested_attributes_for :profile
  has_one :game    , dependent: :destroy
  validates_associated :profile
  validates_associated :game

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

  def help

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user=User.new
      @user.build_profile
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.create_game
      redirect_to root_path
    else

    end

  end

  def show

  end

  def edit

  end

  def update

  end

  def play_game

  end

  def user_input

  end

  private
  def user_params
    params.require(:user).permit(:name, :password, profile_attributes: [:id, :first_name, :last_name, :email, :gender])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper



end

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

app/views/games/play.html.erb
<h1>Games#play</h1>
<p>Find me in app/views/games/play.html.erb</p>

app/views/layouts/_footer.html.haml
%h6 &copy; HangmanGame

app/views/layouts/_header.html.haml
.logo.span5
  %span Hangman
.rightNav.pull-right
  %ul
    %li
      =link_to "Home", root_path
    %li
      =link_to "About", about_path
    %li
      =link_to "SignIn", signin_path

app/views/layouts/application.html.haml
!!!
%html
%head
%title HangmanGame
= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
= javascript_include_tag "application", "data-turbolinks-track" => true
= csrf_meta_tags
%body
  %header
    .container.clearfix
      = render 'layouts/header'
  %section
    .container
      =yield
  %footer
    .container
      = render 'layouts/footer'
=notice
=alert'Successfully added'

app/views/pages/about.html.haml
.container
  %h1 About page come here

app/views/pages/help.html.haml
.container
  %h1 Help Page Come here

app/views/pages/home.html.haml
.container
  .span6
    =image_tag "Hangman.png"
  .span3
    .signupArea
      =link_to "SignUp", signup_path, class:"signupBtn"

app/views/users/new.html.haml
= nested_form_for (@user),html:{class:"form-horizontal"} do |f|
  .control-group
    =f.label :name, class:"control-label"
    .controls
      =f.text_field :name
  .control-group
    =f.label :password, class:"control-label"
    .controls
      =f.password_field :password
  .profileInfo
    =f.fields_for :profile do |prof|
      .control-group
        =prof.label :first_name, class:"control-label"
        .controls
          =prof.text_field :first_name
      .control-group
        =prof.label :last_name, class:"control-label"
        .controls
          =prof.text_field :last_name
      .control-group
        =prof.label :email, class:"control-label"
        .controls
          =prof.text_field :email
      .control-group
        =prof.label :gender ,class:"control-label"
        .controls.clearfix
          %label.span1
            =prof.radio_button :gender ,true,checked: true
            Male
          %label.span2
            =prof.radio_button :gender ,false
            Female
  .control-group
    .controls
      %input{type: "submit", value:"SignUp", class:"btn"}

app/views/users/play_game.html.haml
.container
  %h1 Play Game